// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8CZzQtU7-PS6Cv1EBZnMA-aeyZWffewI',
    appId: '1:145325945041:web:3beca545e45548339415f0',
    messagingSenderId: '145325945041',
    projectId: 'kit305-28118',
    authDomain: 'kit305-28118.firebaseapp.com',
    storageBucket: 'kit305-28118.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMyTxOqCM8NQWWfMHo0aw3U1tLWRPv_To',
    appId: '1:145325945041:android:1be44c7f434422779415f0',
    messagingSenderId: '145325945041',
    projectId: 'kit305-28118',
    storageBucket: 'kit305-28118.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIz2JXr1pkCKxqGbDwXwlkbglKzQ_6CYs',
    appId: '1:145325945041:ios:ce811bcaae76c37a9415f0',
    messagingSenderId: '145325945041',
    projectId: 'kit305-28118',
    storageBucket: 'kit305-28118.firebasestorage.app',
    iosBundleId: 'com.example.tutorial13',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIz2JXr1pkCKxqGbDwXwlkbglKzQ_6CYs',
    appId: '1:145325945041:ios:ce811bcaae76c37a9415f0',
    messagingSenderId: '145325945041',
    projectId: 'kit305-28118',
    storageBucket: 'kit305-28118.firebasestorage.app',
    iosBundleId: 'com.example.tutorial13',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8CZzQtU7-PS6Cv1EBZnMA-aeyZWffewI',
    appId: '1:145325945041:web:c58c1a00248a60179415f0',
    messagingSenderId: '145325945041',
    projectId: 'kit305-28118',
    authDomain: 'kit305-28118.firebaseapp.com',
    storageBucket: 'kit305-28118.firebasestorage.app',
  );
}
